### ISSUE TITLE
problem with images header/thumbnail in post - skeleton

### ISSUE THREAD

**Issue by beamaria** [OleVik/grav-theme-project-space#9]
When trying to add an image to be used as header/thumbnail in post, the dropdown field for images does NOT work and it's impossible to add/display an image. I tried to add manually the image in post folder and in a general user/images folder, but it doesn't work.
Also, the admin setup window is displayed with an already existing user, making therefore impossible to set up the  current user.

<img width="1678" alt="Schermata 2020-04-01 alle 11 48 28" src="https://user-images.githubusercontent.com/11693902/78129255-30c88300-740f-11ea-8f2c-45cd0f6a05a8.png">

**Comment by beamaria** [comment]
Further problem: it is not possible to change/add new categories in theme setup

**Comment by OleVik** [comment]
The issue regarding header-image should be fixed in [v1.2.4](https://github.com/OleVik/grav-theme-project-space/releases/tag/v1.2.4). The skeleton-package was assembled with a dummy-account, incorrectly, and will be updated soon to use the latest stable version of Core and Admin.

Regarding adding/changing categories: This is an upstream issue that requires the Admin-plugin version 1.9 or higher. The values are in fact saved, and displayed in the tool bar on the front-end, but only the testing-versions of Admin render the field correctly.

**Comment by OleVik** [comment]
The latter issue is solved by [v1.0.3](https://github.com/OleVik/grav-skeleton-project-space/releases/tag/v1.0.3) of the skeleton-package, which updates Core, Admin, and the ecosystem, as well as [v1.2.5](https://github.com/OleVik/grav-theme-project-space/releases/tag/v1.2.5) of the theme.
